#!/usr/bin/env zsh

setopt SH_WORD_SPLIT NO_NOMATCH

####################################################################
# wofi_wrun - wofi-dmenu script that simulates 'rofi -show window' #
#                                                                  #
# Author: dmesg00 <dmesg00@duck.com>                               #
# Last update: 15-08-2026                                          #
####################################################################

# Configuration variables
load_theme_path="${HOME}/.wofi"

generate_spaces() {
  num_spaces=${1}
  count_spaces=1
  while (( ${count_spaces} <= ${num_spaces} )) ; do
    echo -n " "
    count_spaces=$(expr ${count_spaces} + 1)
  done
}

check_dependencies() {
  swaymsg &> /dev/null
  error=$?
  if (( ${error} != 0 )) ; then
    echo "   Error: You need install 'swaymsg'" | wofi --dmenu -p "󰈞  window"
    exit
  fi
}

list_applications_icons() {
  swaymsg -t get_tree | jq -r '.. | .nodes?[]? | select(.type == "con" and .focused == false and .name != null) | .name' | while read current_app ; do
    echo "   ${current_app}"
  done
  generate_spaces 75
}

check_dependencies
list_output=$(list_applications_icons | wofi -s ~/.config/wofi/wofi.css --dmenu -i -p "󰈞  window")
run_output=$(echo ${list_output} | cut -c 5-999)
echo "# Selected: ${run_output}"
run_output=$(echo "${run_output}" | cut -d " " -f 1)
if [[ -z "${run_output}" ]] ; then
  echo "# Selection window canceled"
else
  swaymsg "[title=\"${run_output}\"] focus" &> /dev/null
fi
