#!/usr/bin/env zsh

setopt SH_WORD_SPLIT NO_NOMATCH

################################################################
# wofi_run - wofi-dmenu script that simulates 'rofi -show run' #
#                                                              #
# Author: dmesg00 <dmesg00@duck.com>                           #
# Last update: 15-08-2026                                      #
################################################################

# Configuration variables
load_theme_path="${HOME}/.wofi"

generate_spaces() {
  num_spaces=${1}
  count_spaces=1
  while (( ${count_spaces} <= ${num_spaces} )) ; do
    echo -n " "
    count_spaces=$(expr ${count_spaces} + 1)
  done
}

list_binaries() {
  binaries=0
  path_binaries=${PATH}
  count_path=1
  while (( ${binaries} == 0 )) ; do
    current_path=$(echo ${path_binaries} | cut -d ":" -f ${count_path})
    if [[ -z "${current_path}" ]] ; then
      binaries=1
    else
      # Extra code / When /bin is the same that /usr/bin/
      bin_same=$(ls -la ${current_path} | grep "> usr/bin")
      if [[ -z "${bin_same}" ]] ; then
        ls -1 ${current_path}/
        count_path=$(expr ${count_path} + 1)
      else
        count_path=$(expr ${count_path} + 1)
      fi
    fi
  done
}

list_binaries_icons() {
  list_binaries | while read current_binary ; do
    echo "  ${current_binary}"
  done
  generate_spaces 75
}

list_output=$(list_binaries_icons | wofi -s ~/.config/wofi/wofi.css --dmenu -i -p "󰈞  run")
run_output=$(echo "${list_output}" | cut -c4-999)
${run_output}
